import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import WorkoutProvider from "@/context/WorkoutContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FitLog | Workout Library",
  description: "Generated by create FitLog App",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <WorkoutProvider>

          <Navbar></Navbar>

          {children}
        </WorkoutProvider>

        <ToastContainer
          className="fitlog-toast-container"
          position="top-right"
          autoClose={1800}
          hideProgressBar
          newestOnTop={false}
          closeOnClick
          closeButton={false}
          pauseOnHover
          theme="dark"
          toastClassName="fitlog-toast"
          bodyClassName="!m-0 !p-0"
        />

      </body>
    </html>
  );
}
