import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import WorkoutProvider from "@/context/WorkoutContext";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/shared/Footer";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "FitLog | Workout Library",
  description: "Generated by create FitLog App",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${oswald.variable} h-full antialiased`}
    >
      <body className={`${oswald.className} min-h-full flex flex-col`}>

        <WorkoutProvider>

          <Navbar />

          {children}

          <Footer />

        </WorkoutProvider>

        <ToastContainer
          className="fitlog-toast-container"
          position="top-right"
          autoClose={1800}
          hideProgressBar
          newestOnTop={false}
          closeOnClick
          closeButton={false}
          pauseOnHover
          theme="dark"
          toastClassName="fitlog-toast"
        />

      </body>
    </html>
  );
}